package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Atributo generated by hbm2java
 */
public class Atributo  implements java.io.Serializable {


     private int idAtributo;
     private Auditoria auditoria;
     private GenericoItem genericoItem;
     private String descricao;
     private Date dataCadastro;
     private Set objetoAtributos = new HashSet(0);
     private Set atributoOpcaos = new HashSet(0);

    public Atributo() {
    }

	
    public Atributo(int idAtributo) {
        this.idAtributo = idAtributo;
    }
    public Atributo(int idAtributo, Auditoria auditoria, GenericoItem genericoItem, String descricao, Date dataCadastro, Set objetoAtributos, Set atributoOpcaos) {
       this.idAtributo = idAtributo;
       this.auditoria = auditoria;
       this.genericoItem = genericoItem;
       this.descricao = descricao;
       this.dataCadastro = dataCadastro;
       this.objetoAtributos = objetoAtributos;
       this.atributoOpcaos = atributoOpcaos;
    }
   
    public int getIdAtributo() {
        return this.idAtributo;
    }
    
    public void setIdAtributo(int idAtributo) {
        this.idAtributo = idAtributo;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public GenericoItem getGenericoItem() {
        return this.genericoItem;
    }
    
    public void setGenericoItem(GenericoItem genericoItem) {
        this.genericoItem = genericoItem;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getObjetoAtributos() {
        return this.objetoAtributos;
    }
    
    public void setObjetoAtributos(Set objetoAtributos) {
        this.objetoAtributos = objetoAtributos;
    }
    public Set getAtributoOpcaos() {
        return this.atributoOpcaos;
    }
    
    public void setAtributoOpcaos(Set atributoOpcaos) {
        this.atributoOpcaos = atributoOpcaos;
    }




}


