package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AtributoOpcao generated by hbm2java
 */
public class AtributoOpcao  implements java.io.Serializable {


     private int idAtributoOpcao;
     private Atributo atributo;
     private Auditoria auditoria;
     private String opcao;
     private Date dataCadastro;
     private Set objetoAtributoValors = new HashSet(0);

    public AtributoOpcao() {
    }

	
    public AtributoOpcao(int idAtributoOpcao) {
        this.idAtributoOpcao = idAtributoOpcao;
    }
    public AtributoOpcao(int idAtributoOpcao, Atributo atributo, Auditoria auditoria, String opcao, Date dataCadastro, Set objetoAtributoValors) {
       this.idAtributoOpcao = idAtributoOpcao;
       this.atributo = atributo;
       this.auditoria = auditoria;
       this.opcao = opcao;
       this.dataCadastro = dataCadastro;
       this.objetoAtributoValors = objetoAtributoValors;
    }
   
    public int getIdAtributoOpcao() {
        return this.idAtributoOpcao;
    }
    
    public void setIdAtributoOpcao(int idAtributoOpcao) {
        this.idAtributoOpcao = idAtributoOpcao;
    }
    public Atributo getAtributo() {
        return this.atributo;
    }
    
    public void setAtributo(Atributo atributo) {
        this.atributo = atributo;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public String getOpcao() {
        return this.opcao;
    }
    
    public void setOpcao(String opcao) {
        this.opcao = opcao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getObjetoAtributoValors() {
        return this.objetoAtributoValors;
    }
    
    public void setObjetoAtributoValors(Set objetoAtributoValors) {
        this.objetoAtributoValors = objetoAtributoValors;
    }




}


