package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaHistorico generated by hbm2java
 */
public class AuditoriaHistorico  implements java.io.Serializable {


     private int idAuditoriaHistorico;
     private Auditoria auditoria;
     private String dados;
     private Date dataCadastro;

    public AuditoriaHistorico() {
    }

	
    public AuditoriaHistorico(int idAuditoriaHistorico) {
        this.idAuditoriaHistorico = idAuditoriaHistorico;
    }
    public AuditoriaHistorico(int idAuditoriaHistorico, Auditoria auditoria, String dados, Date dataCadastro) {
       this.idAuditoriaHistorico = idAuditoriaHistorico;
       this.auditoria = auditoria;
       this.dados = dados;
       this.dataCadastro = dataCadastro;
    }
   
    public int getIdAuditoriaHistorico() {
        return this.idAuditoriaHistorico;
    }
    
    public void setIdAuditoriaHistorico(int idAuditoriaHistorico) {
        this.idAuditoriaHistorico = idAuditoriaHistorico;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public String getDados() {
        return this.dados;
    }
    
    public void setDados(String dados) {
        this.dados = dados;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }




}


