package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private int idAuditoria;
     private Date dataCadastro;     
     private Set auditoriaHistoricos = new HashSet(0);

    public Auditoria() {
    }

	
    public Auditoria(int idAuditoria) {
        this.idAuditoria = idAuditoria;
    }
    public Auditoria(int idAuditoria, Date dataCadastro, Set auditoriaHistoricos) {
       this.idAuditoria = idAuditoria;
       this.dataCadastro = dataCadastro;
       
       this.auditoriaHistoricos = auditoriaHistoricos;
      
    }
   
    public int getIdAuditoria() {
        return this.idAuditoria;
    }
    
    public void setIdAuditoria(int idAuditoria) {
        this.idAuditoria = idAuditoria;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    
    public Set getAuditoriaHistoricos() {
        return this.auditoriaHistoricos;
    }
    
    public void setAuditoriaHistoricos(Set auditoriaHistoricos) {
        this.auditoriaHistoricos = auditoriaHistoricos;
    }

}


