package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private Auditoria auditoria;
     private GenericoItem genericoItem;
     private PessoaEmpresa pessoaEmpresa;
     private Date dataCadastro;
     private Set contratos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(PessoaEmpresa pessoaEmpresa) {
        this.pessoaEmpresa = pessoaEmpresa;
    }
    public Cliente(Auditoria auditoria, GenericoItem genericoItem, PessoaEmpresa pessoaEmpresa, Date dataCadastro, Set contratos) {
       this.auditoria = auditoria;
       this.genericoItem = genericoItem;
       this.pessoaEmpresa = pessoaEmpresa;
       this.dataCadastro = dataCadastro;
       this.contratos = contratos;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public GenericoItem getGenericoItem() {
        return this.genericoItem;
    }
    
    public void setGenericoItem(GenericoItem genericoItem) {
        this.genericoItem = genericoItem;
    }
    public PessoaEmpresa getPessoaEmpresa() {
        return this.pessoaEmpresa;
    }
    
    public void setPessoaEmpresa(PessoaEmpresa pessoaEmpresa) {
        this.pessoaEmpresa = pessoaEmpresa;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


