package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ComponenteMaquina generated by hbm2java
 */
public class ComponenteMaquina  implements java.io.Serializable {


     private int idComponenteMaquina;
     private Auditoria auditoria;
     private Fabricante fabricante;
     private GenericoItem genericoItem;
     private Maquina maquina;
     private Objeto objeto;
     private Date dataCadastro;

    public ComponenteMaquina() {
    }

	
    public ComponenteMaquina(int idComponenteMaquina) {
        this.idComponenteMaquina = idComponenteMaquina;
    }
    public ComponenteMaquina(int idComponenteMaquina, Auditoria auditoria, Fabricante fabricante, GenericoItem genericoItem, Maquina maquina, Objeto objeto, Date dataCadastro) {
       this.idComponenteMaquina = idComponenteMaquina;
       this.auditoria = auditoria;
       this.fabricante = fabricante;
       this.genericoItem = genericoItem;
       this.maquina = maquina;
       this.objeto = objeto;
       this.dataCadastro = dataCadastro;
    }
   
    public int getIdComponenteMaquina() {
        return this.idComponenteMaquina;
    }
    
    public void setIdComponenteMaquina(int idComponenteMaquina) {
        this.idComponenteMaquina = idComponenteMaquina;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public Fabricante getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(Fabricante fabricante) {
        this.fabricante = fabricante;
    }
    public GenericoItem getGenericoItem() {
        return this.genericoItem;
    }
    
    public void setGenericoItem(GenericoItem genericoItem) {
        this.genericoItem = genericoItem;
    }
    public Maquina getMaquina() {
        return this.maquina;
    }
    
    public void setMaquina(Maquina maquina) {
        this.maquina = maquina;
    }
    public Objeto getObjeto() {
        return this.objeto;
    }
    
    public void setObjeto(Objeto objeto) {
        this.objeto = objeto;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }




}


