package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ContratoMaquina generated by hbm2java
 */
public class ContratoMaquina  implements java.io.Serializable {


     private int idContratoMaquina;
     private Contrato contrato;
     private Maquina maquina;
     private Integer idAuditoria;
     private Date dataCadastro;

    public ContratoMaquina() {
    }

	
    public ContratoMaquina(int idContratoMaquina) {
        this.idContratoMaquina = idContratoMaquina;
    }
    public ContratoMaquina(int idContratoMaquina, Contrato contrato, Maquina maquina, Integer idAuditoria, Date dataCadastro) {
       this.idContratoMaquina = idContratoMaquina;
       this.contrato = contrato;
       this.maquina = maquina;
       this.idAuditoria = idAuditoria;
       this.dataCadastro = dataCadastro;
    }
   
    public int getIdContratoMaquina() {
        return this.idContratoMaquina;
    }
    
    public void setIdContratoMaquina(int idContratoMaquina) {
        this.idContratoMaquina = idContratoMaquina;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public Maquina getMaquina() {
        return this.maquina;
    }
    
    public void setMaquina(Maquina maquina) {
        this.maquina = maquina;
    }
    public Integer getIdAuditoria() {
        return this.idAuditoria;
    }
    
    public void setIdAuditoria(Integer idAuditoria) {
        this.idAuditoria = idAuditoria;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }




}


