package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contato generated by hbm2java
 */
public class Contato  implements java.io.Serializable {


     private int idContato;
     private Auditoria auditoria;
     private String nome;
     private String telefone;
     private String email;
     private Date dataCadastro;
     private Set pessoaEmpresaContatos = new HashSet(0);

    public Contato() {
    }

	
    public Contato(int idContato) {
        this.idContato = idContato;
    }
    public Contato(int idContato, Auditoria auditoria, String nome, String telefone, String email, Date dataCadastro, Set pessoaEmpresaContatos) {
       this.idContato = idContato;
       this.auditoria = auditoria;
       this.nome = nome;
       this.telefone = telefone;
       this.email = email;
       this.dataCadastro = dataCadastro;
       this.pessoaEmpresaContatos = pessoaEmpresaContatos;
    }
   
    public int getIdContato() {
        return this.idContato;
    }
    
    public void setIdContato(int idContato) {
        this.idContato = idContato;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getPessoaEmpresaContatos() {
        return this.pessoaEmpresaContatos;
    }
    
    public void setPessoaEmpresaContatos(Set pessoaEmpresaContatos) {
        this.pessoaEmpresaContatos = pessoaEmpresaContatos;
    }




}


