package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private int idContrato;
     private Cliente cliente;
     private Integer idAuditoria;
     private Date dataCadastro;
     private Set contratoMaquinas = new HashSet(0);

    public Contrato() {
    }

	
    public Contrato(int idContrato) {
        this.idContrato = idContrato;
    }
    public Contrato(int idContrato, Cliente cliente, Integer idAuditoria, Date dataCadastro, Set contratoMaquinas) {
       this.idContrato = idContrato;
       this.cliente = cliente;
       this.idAuditoria = idAuditoria;
       this.dataCadastro = dataCadastro;
       this.contratoMaquinas = contratoMaquinas;
    }
   
    public int getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Integer getIdAuditoria() {
        return this.idAuditoria;
    }
    
    public void setIdAuditoria(Integer idAuditoria) {
        this.idAuditoria = idAuditoria;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getContratoMaquinas() {
        return this.contratoMaquinas;
    }
    
    public void setContratoMaquinas(Set contratoMaquinas) {
        this.contratoMaquinas = contratoMaquinas;
    }




}


