package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fabricante generated by hbm2java
 */
public class Fabricante  implements java.io.Serializable {


     private int idFabricante;
     private Auditoria auditoria;
     private String descricao;
     private Date dataCadastro;
     private Set componenteMaquinas = new HashSet(0);

    public Fabricante() {
    }

	
    public Fabricante(int idFabricante) {
        this.idFabricante = idFabricante;
    }
    public Fabricante(int idFabricante, Auditoria auditoria, String descricao, Date dataCadastro, Set componenteMaquinas) {
       this.idFabricante = idFabricante;
       this.auditoria = auditoria;
       this.descricao = descricao;
       this.dataCadastro = dataCadastro;
       this.componenteMaquinas = componenteMaquinas;
    }
   
    public int getIdFabricante() {
        return this.idFabricante;
    }
    
    public void setIdFabricante(int idFabricante) {
        this.idFabricante = idFabricante;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getComponenteMaquinas() {
        return this.componenteMaquinas;
    }
    
    public void setComponenteMaquinas(Set componenteMaquinas) {
        this.componenteMaquinas = componenteMaquinas;
    }




}


