package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Generico generated by hbm2java
 */
public class Generico  implements java.io.Serializable {


     private int idGenerico;
     private Auditoria auditoria;
     private String nome;
     private String descricao;
     private Date dataCadastro;
     private Set genericoItems = new HashSet(0);

    public Generico() {
    }

	
    public Generico(int idGenerico) {
        this.idGenerico = idGenerico;
    }
    public Generico(int idGenerico, Auditoria auditoria, String nome, String descricao, Date dataCadastro, Set genericoItems) {
       this.idGenerico = idGenerico;
       this.auditoria = auditoria;
       this.nome = nome;
       this.descricao = descricao;
       this.dataCadastro = dataCadastro;
       this.genericoItems = genericoItems;
    }
   
    public int getIdGenerico() {
        return this.idGenerico;
    }
    
    public void setIdGenerico(int idGenerico) {
        this.idGenerico = idGenerico;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getGenericoItems() {
        return this.genericoItems;
    }
    
    public void setGenericoItems(Set genericoItems) {
        this.genericoItems = genericoItems;
    }




}


