package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GenericoItem generated by hbm2java
 */
public class GenericoItem  implements java.io.Serializable {


     private int idGenericoItem;
     private Auditoria auditoria;
     private Generico generico;
     private String descricao;
     private String sigla;
     private Boolean ativo;
     private Date dataCadastro;
     private Set clientes = new HashSet(0);
     private Set maquinasForIdCategoriaMaquina = new HashSet(0);
     private Set objetos = new HashSet(0);
     private Set maquinasForIdTipoMaquina = new HashSet(0);
     private Set componenteMaquinas = new HashSet(0);
     private Set maquinasForIdAmbienteFuncionamento = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set atributos = new HashSet(0);

    public GenericoItem() {
    }

	
    public GenericoItem(int idGenericoItem) {
        this.idGenericoItem = idGenericoItem;
    }
    public GenericoItem(int idGenericoItem, Auditoria auditoria, Generico generico, String descricao, String sigla, Boolean ativo, Date dataCadastro, Set clientes, Set maquinasForIdCategoriaMaquina, Set objetos, Set maquinasForIdTipoMaquina, Set componenteMaquinas, Set maquinasForIdAmbienteFuncionamento, Set usuarios, Set atributos) {
       this.idGenericoItem = idGenericoItem;
       this.auditoria = auditoria;
       this.generico = generico;
       this.descricao = descricao;
       this.sigla = sigla;
       this.ativo = ativo;
       this.dataCadastro = dataCadastro;
       this.clientes = clientes;
       this.maquinasForIdCategoriaMaquina = maquinasForIdCategoriaMaquina;
       this.objetos = objetos;
       this.maquinasForIdTipoMaquina = maquinasForIdTipoMaquina;
       this.componenteMaquinas = componenteMaquinas;
       this.maquinasForIdAmbienteFuncionamento = maquinasForIdAmbienteFuncionamento;
       this.usuarios = usuarios;
       this.atributos = atributos;
    }
   
    public int getIdGenericoItem() {
        return this.idGenericoItem;
    }
    
    public void setIdGenericoItem(int idGenericoItem) {
        this.idGenericoItem = idGenericoItem;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public Generico getGenerico() {
        return this.generico;
    }
    
    public void setGenerico(Generico generico) {
        this.generico = generico;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Boolean getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getMaquinasForIdCategoriaMaquina() {
        return this.maquinasForIdCategoriaMaquina;
    }
    
    public void setMaquinasForIdCategoriaMaquina(Set maquinasForIdCategoriaMaquina) {
        this.maquinasForIdCategoriaMaquina = maquinasForIdCategoriaMaquina;
    }
    public Set getObjetos() {
        return this.objetos;
    }
    
    public void setObjetos(Set objetos) {
        this.objetos = objetos;
    }
    public Set getMaquinasForIdTipoMaquina() {
        return this.maquinasForIdTipoMaquina;
    }
    
    public void setMaquinasForIdTipoMaquina(Set maquinasForIdTipoMaquina) {
        this.maquinasForIdTipoMaquina = maquinasForIdTipoMaquina;
    }
    public Set getComponenteMaquinas() {
        return this.componenteMaquinas;
    }
    
    public void setComponenteMaquinas(Set componenteMaquinas) {
        this.componenteMaquinas = componenteMaquinas;
    }
    public Set getMaquinasForIdAmbienteFuncionamento() {
        return this.maquinasForIdAmbienteFuncionamento;
    }
    
    public void setMaquinasForIdAmbienteFuncionamento(Set maquinasForIdAmbienteFuncionamento) {
        this.maquinasForIdAmbienteFuncionamento = maquinasForIdAmbienteFuncionamento;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getAtributos() {
        return this.atributos;
    }
    
    public void setAtributos(Set atributos) {
        this.atributos = atributos;
    }




}


