package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Maquina generated by hbm2java
 */
public class Maquina  implements java.io.Serializable {


     private int idMaquina;
     private Auditoria auditoria;
     private GenericoItem genericoItemByIdCategoriaMaquina;
     private GenericoItem genericoItemByIdTipoMaquina;
     private GenericoItem genericoItemByIdAmbienteFuncionamento;
     private Maquina maquina;
     private String descricao;
     private String modelo;
     private Date dataUltimaRevisao;
     private Date dataCadastro;
     private Set componenteMaquinas = new HashSet(0);
     private Set contratoMaquinas = new HashSet(0);
     private Set maquinas = new HashSet(0);

    public Maquina() {
    }

	
    public Maquina(int idMaquina) {
        this.idMaquina = idMaquina;
    }
    public Maquina(int idMaquina, Auditoria auditoria, GenericoItem genericoItemByIdCategoriaMaquina, GenericoItem genericoItemByIdTipoMaquina, GenericoItem genericoItemByIdAmbienteFuncionamento, Maquina maquina, String descricao, String modelo, Date dataUltimaRevisao, Date dataCadastro, Set componenteMaquinas, Set contratoMaquinas, Set maquinas) {
       this.idMaquina = idMaquina;
       this.auditoria = auditoria;
       this.genericoItemByIdCategoriaMaquina = genericoItemByIdCategoriaMaquina;
       this.genericoItemByIdTipoMaquina = genericoItemByIdTipoMaquina;
       this.genericoItemByIdAmbienteFuncionamento = genericoItemByIdAmbienteFuncionamento;
       this.maquina = maquina;
       this.descricao = descricao;
       this.modelo = modelo;
       this.dataUltimaRevisao = dataUltimaRevisao;
       this.dataCadastro = dataCadastro;
       this.componenteMaquinas = componenteMaquinas;
       this.contratoMaquinas = contratoMaquinas;
       this.maquinas = maquinas;
    }
   
    public int getIdMaquina() {
        return this.idMaquina;
    }
    
    public void setIdMaquina(int idMaquina) {
        this.idMaquina = idMaquina;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public GenericoItem getGenericoItemByIdCategoriaMaquina() {
        return this.genericoItemByIdCategoriaMaquina;
    }
    
    public void setGenericoItemByIdCategoriaMaquina(GenericoItem genericoItemByIdCategoriaMaquina) {
        this.genericoItemByIdCategoriaMaquina = genericoItemByIdCategoriaMaquina;
    }
    public GenericoItem getGenericoItemByIdTipoMaquina() {
        return this.genericoItemByIdTipoMaquina;
    }
    
    public void setGenericoItemByIdTipoMaquina(GenericoItem genericoItemByIdTipoMaquina) {
        this.genericoItemByIdTipoMaquina = genericoItemByIdTipoMaquina;
    }
    public GenericoItem getGenericoItemByIdAmbienteFuncionamento() {
        return this.genericoItemByIdAmbienteFuncionamento;
    }
    
    public void setGenericoItemByIdAmbienteFuncionamento(GenericoItem genericoItemByIdAmbienteFuncionamento) {
        this.genericoItemByIdAmbienteFuncionamento = genericoItemByIdAmbienteFuncionamento;
    }
    public Maquina getMaquina() {
        return this.maquina;
    }
    
    public void setMaquina(Maquina maquina) {
        this.maquina = maquina;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Date getDataUltimaRevisao() {
        return this.dataUltimaRevisao;
    }
    
    public void setDataUltimaRevisao(Date dataUltimaRevisao) {
        this.dataUltimaRevisao = dataUltimaRevisao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getComponenteMaquinas() {
        return this.componenteMaquinas;
    }
    
    public void setComponenteMaquinas(Set componenteMaquinas) {
        this.componenteMaquinas = componenteMaquinas;
    }
    public Set getContratoMaquinas() {
        return this.contratoMaquinas;
    }
    
    public void setContratoMaquinas(Set contratoMaquinas) {
        this.contratoMaquinas = contratoMaquinas;
    }
    public Set getMaquinas() {
        return this.maquinas;
    }
    
    public void setMaquinas(Set maquinas) {
        this.maquinas = maquinas;
    }




}


