package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Objeto generated by hbm2java
 */
public class Objeto  implements java.io.Serializable {


     private int idObjeto;
     private Auditoria auditoria;
     private GenericoItem genericoItem;
     private String descricao;
     private Date dataCadastro;
     private Set objetoAtributos = new HashSet(0);
     private Set componenteMaquinas = new HashSet(0);

    public Objeto() {
    }

	
    public Objeto(int idObjeto) {
        this.idObjeto = idObjeto;
    }
    public Objeto(int idObjeto, Auditoria auditoria, GenericoItem genericoItem, String descricao, Date dataCadastro, Set objetoAtributos, Set componenteMaquinas) {
       this.idObjeto = idObjeto;
       this.auditoria = auditoria;
       this.genericoItem = genericoItem;
       this.descricao = descricao;
       this.dataCadastro = dataCadastro;
       this.objetoAtributos = objetoAtributos;
       this.componenteMaquinas = componenteMaquinas;
    }
   
    public int getIdObjeto() {
        return this.idObjeto;
    }
    
    public void setIdObjeto(int idObjeto) {
        this.idObjeto = idObjeto;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public GenericoItem getGenericoItem() {
        return this.genericoItem;
    }
    
    public void setGenericoItem(GenericoItem genericoItem) {
        this.genericoItem = genericoItem;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getObjetoAtributos() {
        return this.objetoAtributos;
    }
    
    public void setObjetoAtributos(Set objetoAtributos) {
        this.objetoAtributos = objetoAtributos;
    }
    public Set getComponenteMaquinas() {
        return this.componenteMaquinas;
    }
    
    public void setComponenteMaquinas(Set componenteMaquinas) {
        this.componenteMaquinas = componenteMaquinas;
    }




}


