package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ObjetoAtributo generated by hbm2java
 */
public class ObjetoAtributo  implements java.io.Serializable {


     private int idObjetoAtributo;
     private Atributo atributo;
     private Auditoria auditoria;
     private Objeto objeto;
     private String valor;
     private Date dataCadastro;
     private Set objetoAtributoValors = new HashSet(0);

    public ObjetoAtributo() {
    }

	
    public ObjetoAtributo(int idObjetoAtributo) {
        this.idObjetoAtributo = idObjetoAtributo;
    }
    public ObjetoAtributo(int idObjetoAtributo, Atributo atributo, Auditoria auditoria, Objeto objeto, String valor, Date dataCadastro, Set objetoAtributoValors) {
       this.idObjetoAtributo = idObjetoAtributo;
       this.atributo = atributo;
       this.auditoria = auditoria;
       this.objeto = objeto;
       this.valor = valor;
       this.dataCadastro = dataCadastro;
       this.objetoAtributoValors = objetoAtributoValors;
    }
   
    public int getIdObjetoAtributo() {
        return this.idObjetoAtributo;
    }
    
    public void setIdObjetoAtributo(int idObjetoAtributo) {
        this.idObjetoAtributo = idObjetoAtributo;
    }
    public Atributo getAtributo() {
        return this.atributo;
    }
    
    public void setAtributo(Atributo atributo) {
        this.atributo = atributo;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public Objeto getObjeto() {
        return this.objeto;
    }
    
    public void setObjeto(Objeto objeto) {
        this.objeto = objeto;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Set getObjetoAtributoValors() {
        return this.objetoAtributoValors;
    }
    
    public void setObjetoAtributoValors(Set objetoAtributoValors) {
        this.objetoAtributoValors = objetoAtributoValors;
    }




}


