package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PessoaEmpresaContato generated by hbm2java
 */
public class PessoaEmpresaContato  implements java.io.Serializable {


     private int idPessoaEmpresaContato;
     private Auditoria auditoria;
     private Contato contato;
     private PessoaEmpresa pessoaEmpresa;
     private Date dataCadastro;

    public PessoaEmpresaContato() {
    }

	
    public PessoaEmpresaContato(int idPessoaEmpresaContato) {
        this.idPessoaEmpresaContato = idPessoaEmpresaContato;
    }
    public PessoaEmpresaContato(int idPessoaEmpresaContato, Auditoria auditoria, Contato contato, PessoaEmpresa pessoaEmpresa, Date dataCadastro) {
       this.idPessoaEmpresaContato = idPessoaEmpresaContato;
       this.auditoria = auditoria;
       this.contato = contato;
       this.pessoaEmpresa = pessoaEmpresa;
       this.dataCadastro = dataCadastro;
    }
   
    public int getIdPessoaEmpresaContato() {
        return this.idPessoaEmpresaContato;
    }
    
    public void setIdPessoaEmpresaContato(int idPessoaEmpresaContato) {
        this.idPessoaEmpresaContato = idPessoaEmpresaContato;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public Contato getContato() {
        return this.contato;
    }
    
    public void setContato(Contato contato) {
        this.contato = contato;
    }
    public PessoaEmpresa getPessoaEmpresa() {
        return this.pessoaEmpresa;
    }
    
    public void setPessoaEmpresa(PessoaEmpresa pessoaEmpresa) {
        this.pessoaEmpresa = pessoaEmpresa;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }




}


