package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PessoaEmpresaEndereco generated by hbm2java
 */
public class PessoaEmpresaEndereco  implements java.io.Serializable {


     private int idPessoaEmpresaEndereco;
     private Auditoria auditoria;
     private PessoaEmpresa pessoaEmpresa;
     private String cep;
     private String numero;
     private Date dataCadastro;

    public PessoaEmpresaEndereco() {
    }

	
    public PessoaEmpresaEndereco(int idPessoaEmpresaEndereco) {
        this.idPessoaEmpresaEndereco = idPessoaEmpresaEndereco;
    }
    public PessoaEmpresaEndereco(int idPessoaEmpresaEndereco, Auditoria auditoria, PessoaEmpresa pessoaEmpresa, String cep, String numero, Date dataCadastro) {
       this.idPessoaEmpresaEndereco = idPessoaEmpresaEndereco;
       this.auditoria = auditoria;
       this.pessoaEmpresa = pessoaEmpresa;
       this.cep = cep;
       this.numero = numero;
       this.dataCadastro = dataCadastro;
    }
   
    public int getIdPessoaEmpresaEndereco() {
        return this.idPessoaEmpresaEndereco;
    }
    
    public void setIdPessoaEmpresaEndereco(int idPessoaEmpresaEndereco) {
        this.idPessoaEmpresaEndereco = idPessoaEmpresaEndereco;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public PessoaEmpresa getPessoaEmpresa() {
        return this.pessoaEmpresa;
    }
    
    public void setPessoaEmpresa(PessoaEmpresa pessoaEmpresa) {
        this.pessoaEmpresa = pessoaEmpresa;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }




}


