package Business.Entity.Map;
// Generated 23/10/2015 01:12:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PessoaEmpresa generated by hbm2java
 */
public class PessoaEmpresa  implements java.io.Serializable {


     private int idPessoaEmpresa;
     private Auditoria auditoria;
     private String nome;
     private String cnpj;
     private String cpf;
     private Date dataCadastro;
     private Cliente cliente;
     private Set pessoaEmpresaEnderecos = new HashSet(0);
     private Set pessoaEmpresaContatos = new HashSet(0);
     private Usuario usuario;

    public PessoaEmpresa() {
    }

	
    public PessoaEmpresa(int idPessoaEmpresa) {
        this.idPessoaEmpresa = idPessoaEmpresa;
    }
    public PessoaEmpresa(int idPessoaEmpresa, Auditoria auditoria, String nome, String cnpj, String cpf, Date dataCadastro, Cliente cliente, Set pessoaEmpresaEnderecos, Set pessoaEmpresaContatos, Usuario usuario) {
       this.idPessoaEmpresa = idPessoaEmpresa;
       this.auditoria = auditoria;
       this.nome = nome;
       this.cnpj = cnpj;
       this.cpf = cpf;
       this.dataCadastro = dataCadastro;
       this.cliente = cliente;
       this.pessoaEmpresaEnderecos = pessoaEmpresaEnderecos;
       this.pessoaEmpresaContatos = pessoaEmpresaContatos;
       this.usuario = usuario;
    }
   
    public int getIdPessoaEmpresa() {
        return this.idPessoaEmpresa;
    }
    
    public void setIdPessoaEmpresa(int idPessoaEmpresa) {
        this.idPessoaEmpresa = idPessoaEmpresa;
    }
    public Auditoria getAuditoria() {
        return this.auditoria;
    }
    
    public void setAuditoria(Auditoria auditoria) {
        this.auditoria = auditoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Set getPessoaEmpresaEnderecos() {
        return this.pessoaEmpresaEnderecos;
    }
    
    public void setPessoaEmpresaEnderecos(Set pessoaEmpresaEnderecos) {
        this.pessoaEmpresaEnderecos = pessoaEmpresaEnderecos;
    }
    public Set getPessoaEmpresaContatos() {
        return this.pessoaEmpresaContatos;
    }
    
    public void setPessoaEmpresaContatos(Set pessoaEmpresaContatos) {
        this.pessoaEmpresaContatos = pessoaEmpresaContatos;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


